### ISSUE TITLE
Don't overwrite old styles when updating nodes with inline styles.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#537]
The current strategy for applying inline styles is to merge the old node styles with the new node styles, producing a new set of styles that has all the keys, iterate over them, apply the new styles and **erase** the old styles.

#### Old Styles
```css
{
 color: red;
 fontSize: 14;
}
```
#### New Styles
```css
{
 color: blue;
}
```

#### Result
```css
{
 color: blue;
}
```

Should we change this behavior and instead produce the following result:

#### Proposed Result
```css
{
 color: blue;
 fontSize: 14;
}
```

/cc @mindplay-dk @zaceno

**Comment by Swizz** [comment]
So

```css
{
 color: blue;
 fontSize: undefined;
}
```

Will allow us to remove the `fontSize` property ?
