### ISSUE TITLE
eslint jsx no-unused-vars

### ISSUE THREAD

**Issue by willin** [hyperapp/hyperapp#557]
```js
// _footer.js
import { h } from 'hyperapp';

export default () => (
  <footer>
    Copyright &copy; 2002 ~ {(new Date()).getFullYear()} Willin Wang
  </footer>
);
```
```js
// layout.js
import { h } from 'hyperapp';
import PageFooter from './_footer';
// Error: [eslint] 'PageFooter' is defined but never used. (no-unused-vars)

export default () => (
  <div id="container">
    <PageFooter />
  </div>
);
```

---

eslint config:

```yml
root: true
extends: dwing
env:
  browser: true
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - html
globals:
  hyperapp: true
rules:
  'no-unused-vars': [2, { 'varsIgnorePattern': '^h$' }]
```
